#!/usr/bin/env bash
# This file was generated by Chef.
# Do NOT modify this file by hand!

cd src
chown www-data -R pub/static
chown www-data -R pub/media
chown www-data -R app/etc/
chown www-data -R var
chown www-data -R generated