name 'zikraft'
maintainer 'gogoluxecs'
maintainer_email 'gogo_luxecs@yahoo.com'
license 'all_rights'
description 'Installs/Configures zikraft'
long_description 'Installs/Configures cherrypi application'
version '0.1.0'
