name 'zikraft'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures zikraft'
long_description 'Installs/Configures zikraft'
version '0.1.0'
