sudo: required
dist: trusty

# install the pre-release chef-dk.  Use chef-stable-precise to install the stable release
addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

branches:
  only:
    - master

services: docker

env:
  matrix:
    - INSTANCE=debian-8
    - INSTANCE=centos-7

script: cd cookbooks/lytc; KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - script:
      - cd cookbooks/lytc; /opt/chefdk/bin/chef exec rake spec
