name 'atlasck'
maintainer 'gogoluxecs'
maintainer_email 'georgi.lambov@gmail.com'
license 'GPL'
description 'Installs/Configures atlasck'
long_description 'Installs/Configures atlasck'
version '0.1.0'

depends 'apt', '~> 4.0.2'
depends 'mysql', '~> 8.0'
