name 'atlasck'
maintainer 'gogoluxecs'
maintainer_email 'gogo_luxecs@yahoo.com'
license 'GPL'
description 'Installs/Configures atlasck'
long_description 'Installs/Configures atlasck'
version '0.1.0'

depends 'mysql', '~> 8.0'
depends 'database', '~> 5.1.2'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'tomcat', '~> 2.3.1'
