name 'wiki'
maintainer 'gogoluxecs'
maintainer_email 'gogo_luxecs@yahoo.com'
license 'all_rights'
description 'Installs/Configures wiki'
long_description 'Installs/Configures moin-moin'
version '0.1.0'
