name 'gitserver'
maintainer 'gogoluxecs'
maintainer_email 'gogo_luxecs@yahoo.com'
license 'all_rights'
description 'Installs/Configures git server'
long_description 'Installs/Configures wraps gitolite'
version '0.1.0'
