name 'gitserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures gitserver'
long_description 'Installs/Configures gitserver'
version '0.1.0'
