name 'lytc'
maintainer 'gogoluxecs'
maintainer_email 'gogo_luxecs@yahoo.com'
license 'GPL'
description 'Installs/Configures lytc'
long_description 'Basic cookbook used in high level cookbooks'
version '0.1.0'

depends 'apt', '~> 4.0.2'
depends 'logrotate', '~> 1.9.2'
depends 'mongodb', '~> 0.16.2'
depends 'htop', '~> 2.0.0'
