default['inniti']['flow']['dir']['src'] = '/var/www/inniti-backend/Flow_MES'
default['inniti']['flow']['dir']['target'] = '/home/inniti/app'
default['inniti']['flow']['config'][node.environment] = '/src/resources/config-prod.properties'
default['inniti']['flow']['jar'] = 'Flow_MES-1.0-jar-with-dependencies.jar'
default['inniti']['user']['name'] = 'inniti'
